import {Router} from "express";
import {signUp, updateProfile, getProfile, searchUser, uploadFile} from "./sign-Up.js";
import signIn from "./sign-In.js";
import {addBook, fetchBooks, updateBookReview, startReading, fetchCurrentlyReadingBooks, fetchReview} from "./book-Shelf.js";
import {fetchUpdatesByfriends, updateProgress, book, bookDetails} from "./book-Shelf.js";
import { addFriend, friendRequests, acknowledgeFriendRequest, fetchFriends} from "./friend.js";

const router = Router();
router.post('/signin', signIn);
router.post('/signup', signUp);
router.post('/addbooktoshelf', addBook);
router.post('/books', fetchBooks);
router.post('/updaterating', updateBookReview);
router.post('/startreading', startReading);
router.post('/currentlyreadingbooks', fetchCurrentlyReadingBooks);
router.post('/fetchupdates', fetchUpdatesByfriends);
router.post('/updateprogress', updateProgress);
router.post('/profile', updateProfile);
router.post('/getprofile', getProfile);
router.post('/searchuser', searchUser);
router.post('/addfriend', addFriend);
router.post('/friendrequests', friendRequests);
router.post('/acknowledgefriendrequest', acknowledgeFriendRequest);
router.post('/fetchfriends', fetchFriends);
router.post('/fetchReview', fetchReview);
router.post('/book', book);
router.post('/bookDetails', bookDetails);
router.post('/uploadFile', uploadFile);
export default router;